apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: buooh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: nginx
        image: "public.ecr.aws/nginx/nginx"
        ports:
        - containerPort: 3003
        resources:
          requests:
            cpu: "1"
            memory: "64Mi"