apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: buooh
spec:
  replicas: 4
  selector:
    matchLabels:
      app: admin
      workload: buooh
  template:
    metadata:
      labels:
        app: admin
        workload: buooh
    spec:
      containers:
        - name: nginx
          image: "public.ecr.aws/nginx/nginx"
          ports:
          - containerPort: 9091
          resources:
            requests:
              cpu: "1"
              memory: "64Mi"