apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel
  namespace: buooh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: panel
      workload: buooh
  template:
    metadata:
      labels:
        app: panel
        workload: buooh
    spec:
      containers:
      - name: nginx
        image: "public.ecr.aws/nginx/nginx"
        ports:
        - containerPort: 3004
        resources:
          requests:
            cpu: "1"
            memory: "64Mi"