apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: alb-ingress
  namespace: default
spec:
  rules:
  - host: example.com  # Replace with your desired hostname
  - http:
      paths:      
      - backend:
          service:
            name: orders-service
            port: 
              number: 3003
        path: /v1/orders
        pathType: Prefix
      - backend:
          service:
            name: products-service
            port: 
              number: 3004
        path: /v1/products
        pathType: Prefix
